core/base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),

    path('propostas/', views.propostas, name='propostas'),
    path('proposta/', views.proposta, name='proposta'),
    path('proposta/<int:id>/', views.proposta, name='proposta'),
    path(
        'proposta/<int:id>/<slug:situacao>/', views.proposta, name='proposta'),
    path(
        'proposta/documento/<int:id>/',
        views.proposta_documento,
        name='proposta_documento'),
    path(
        'proposta/arquivo/extrato/<int:id>/',
        views.proposta_arquivo_extrato,
        name='proposta_arquivo_extrato'),
    path(
        'proposta/empenhar/<int:id>/',
        views.proposta_empenhar,
        name='proposta_empenhar'),
    path(
        'proposta/excluir/<int:id>/',
        views.proposta_excluir,
        name='proposta_excluir'),

    path('convenios/', views.convenios, name='convenios'),
    path(
        'convenio/<int:convenio_id>/projeto/controle/',
        views.convenio_projeto_controle,
        name='convenio_projeto_controle'),
    path(
        'convenio/aprovar/projeto/<int:id>/',
        views.convenio_aprovar_projeto,
        name='convenio_aprovar_projeto'),
    path(
        'convenio/licitar/projeto/<int:id>/',
        views.convenio_licitar_projeto,
        name='convenio_licitar_projeto'),
    path(
        'convenio/aprovar/licitacao/<int:id>/',
        views.convenio_aprovar_licitacao,
        name='convenio_aprovar_licitacao'),
    path(
        'convenio/recurso/em/conta/<int:id>/',
        views.convenio_recurso_conta,
        name='convenio_recurso_conta'),
    path(
        'convenio/concluir/<int:id>/',
        views.convenio_concluir, name='convenio_concluir'),
    path(
        'convenio/concluir/prestacao/contas/<int:id>/',
        views.convenio_concluir_prestacao_contas,
        name='convenio_concluir_prestacao_contas'),
    path(
        'convenio/excluir/<int:id>/',
        views.convenio_excluir, name='convenio_excluir'),
    path(
        'arquivo/extrato/<int:id>/',
        views.arquivo_extrato, name='arquivo_extrato'),

    path('servicos/', views.servicos, name='servicos'),
    path('servico/', views.servico, name='servico'),
    path(
        'servico/excluir/<int:id>/',
        views.servico_excluir, name='servico_excluir'),

    path('projetos/', views.projetos, name='projetos'),
    path('projeto/<int:id>/', views.projeto, name='projeto'),
    path('projeto/', views.projeto, name='projeto'),
    path('projeto/<int:id>/itens/', views.projeto_itens, name='projeto_itens'),
    path(
        'projeto/<int:projeto_id>/item/',
        views.projeto_item, name='projeto_item'),
    path(
        'projeto/<int:projeto_id>/item/<int:id>/',
        views.projeto_item, name='projeto_item'),
    path(
        'projeto/<int:convenio_id>/controle/',
        views.projeto_controle, name='projeto_controle'),
    path(
        'projeto/controle/<int:controle_id>/item/',
        views.projeto_controle_item, name='projeto_controle_item'),

    path('itens/', views.itens, name='itens'),
    path('item/<int:id>/', views.item, name='item'),
    path('item/', views.item, name='item'),
    path('opcoes/', views.opcoes, name='opcoes'),
    path('opcao/<int:id>/', views.opcao, name='opcao'),
    path('opcao/', views.opcao, name='opcao'),
    path('alternativas/', views.alternativas, name='alternativas'),
    path('alternativa/<int:id>/', views.alternativa, name='alternativa'),
    path('alternativa/', views.alternativa, name='alternativa'),
    path(
        'itens/alternativas/',
        views.itens_alternativas, name='itens_alternativas'),
    path(
        'item/alternativas/<int:id>/',
        views.item_alternativas, name='item_alternativas'),
    path(
        'item/alternativas/',
        views.item_alternativas, name='item_alternativas'),
    path('check/list/<int:id>/', views.check_list, name='check_list'),
    path('protocolo/<int:convenio_id>/', views.protocolo, name='protocolo'),
    path('protocolos/<int:convenio_id>/', views.protocolos, name='protocolos'),
    path(
        'protocolo/resolver/<int:id>/',
        views.protocolo_resolver, name='protocolo_resolver'),
    path(
        'protocolo/excluir/<int:id>/',
        views.protocolo_excluir, name='protocolo_excluir'),
    path(
        'protocolo/dados-bancarios/<int:convenio_id>/',
        views.protocolo_dados_bancarios, name='protocolo_dados_bancarios'),
    path(
        'protocolo/empresa-contratada/<int:convenio_id>/',
        views.protocolo_empresa_contratada,
        name='protocolo_empresa_contratada'),

    path(
        'protocolo/execucao-convenente/<int:convenio_id>/',
        views.protocolo_execucao_convenente,
        name='protocolo_execucao_convenente'),
    path(
        'protocolo/execucao-convenente/<int:convenio_id>/<int:execucao_convenente_id>/',
        views.protocolo_execucao_convenente,
        name='protocolo_execucao_convenente'),
    path(
        'protocolo/execucao-convenente/excluir/<int:id>/',
        views.protocolo_execucao_convenente_excluir,
        name='protocolo_execucao_convenente_excluir'
    ),

    path(
        'protocolo/execucao-concedente/<int:convenio_id>/',
        views.protocolo_execucao_concedente,
        name='protocolo_execucao_concedente'),
    path(
        'protocolo/execucao-concedente/<int:convenio_id>/<int:execucao_concedente_id>/',
        views.protocolo_execucao_concedente,
        name='protocolo_execucao_concedente'),
    path(
        'protocolo/execucao-concedente/excluir/<int:id>/',
        views.protocolo_execucao_concedente_excluir,
        name='protocolo_execucao_concedente_excluir'
    ),

    path('atividades/<int:convenio_id>/', views.atividades, name='atividades'),
    path(
        'atividade/resolver/<int:id>/',
        views.atividade_resolver, name='atividade_resolver'),
    path(
        'licenciamentos/ambientais/<int:convenio_id>/',
        views.licenciamentos_ambientais,
        name='licenciamentos_ambientais'),
    path(
        'licenciamento/resolver/<int:id>/',
        views.licenciamento_resolver, name='licenciamento_resolver'),

    path('declaracoes/', views.declaracoes, name='declaracoes'),

    path('atualiza_data_hora_criacao/', views.atualiza_data_hora_criacao, name='atualiza_data_hora_criacao'),

]

core/reports/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('propostas/', views.PropostasPDFView.as_view(), name='relatorio-propostas'),
    path('convenios/', views.ConveniosPDFView.as_view(), name='relatorio-convenios'),
    path('servicos/', views.ServicosPDFView.as_view(), name='relatorio-servicos'),
    path(
        'convenio/<int:convenio_id>/projeto/controle/',
        views.ElaboracaoProjetoPDFView.as_view(), name='relatorio-convenio-projeto-controle'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView


favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    re_path('favicon.ico', favicon_view),
    path('api/', include('core.api.urls')),
    path('', include('core.base.urls')),
    path('relatorios/', include('core.reports.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Administrador Agiliza - Convênios'

core/base/models.py
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from ordered_model.models import OrderedModelBase
from rest_framework.authtoken.models import Token


class Cliente(models.Model):
    nome = models.CharField(max_length=250, blank=False, null=False)
    email = models.CharField(max_length=200, blank=False, null=False)
    cnpj = models.CharField(_('CNPJ'), max_length=20, blank=False, null=False)

    endereco = models.CharField(max_length=200, blank=True, null=True)
    cep = models.CharField(_('CEP'), max_length=20, blank=True, null=True)
    bairro = models.CharField(max_length=150, blank=True, null=True)
    cidade = models.CharField(max_length=150, blank=True, null=True)
    uf = models.CharField(_('UF'), max_length=5, blank=True, null=True)
    telefone = models.CharField(max_length=15, blank=True, null=True)
    data_criacao = models.DateField(_('Data de Criação'), auto_now=True, blank=False, null=False)


class Prefeitura(Cliente):
    # campo do tipo imagem, com o modelo de papel timbrado da prefeitura
    timbre = models.ImageField(upload_to='uploads/%Y/%m/%d', max_length=150, blank=True, null=True)

    prefeito = models.ForeignKey('Prefeito', on_delete=models.CASCADE, blank=False, null=False)
    secretario_obras = models.ForeignKey('SecretarioDeObras', on_delete=models.CASCADE, blank=True, null=True)
    secretario_financeiro = models.ForeignKey('SecretarioFinanceiro', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.nome


class Profissional(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    nome = models.CharField(max_length=200, blank=False, null=False)
    cpf = models.CharField(_('CPF'), max_length=20, blank=False, null=False)
    telefone = models.CharField(max_length=20, blank=False, null=False)
    email = models.CharField(max_length=200, blank=False, null=False)
    cargo = models.ForeignKey('Cargo', on_delete=models.CASCADE, blank=True, null=True)
    data_criacao = models.DateField(_('Data de Criação'), auto_now=True, blank=False, null=False)

    class Meta:
        verbose_name = 'profissional'
        verbose_name_plural = 'profissionais'

    def __str__(self):
        return self.nome


class Cargo(models.Model):
    descricao = models.CharField(max_length=200, blank=False, null=False)
    data_criacao = models.DateField(_('Data de Criação'), auto_now=True, blank=False, null=False)

    class Meta:
        verbose_name = _('cargo')
        verbose_name_plural = _('cargos')

    def __str__(self):
        return self.descricao


class Prefeito(Profissional):

    class Meta:
        verbose_name = _('prefeito')
        verbose_name_plural = _('prefeitos')


class Responsavel(Profissional):

    class Meta:
        verbose_name = _('responsável')
        verbose_name_plural = _('responsáveis')


class SecretarioDeObras(Profissional):

    class Meta:
        verbose_name = _('secretário de obras')
        verbose_name_plural = _('secretários de obras')


class SecretarioFinanceiro(Profissional):

    class Meta:
        verbose_name = _('secretário financeiro')
        verbose_name_plural = _('secretários financeiro')


class Proposta(models.Model):

    class SituacaoChoice(models.TextChoices):
        EM_ANALISE = 'em-analise', _('Em análise')
        EMPENHADO = 'empenhada', _('Empenhada')
        APROVADO = 'aprovada', _('Aprovada')
        REPROVADO = 'reprovada', _('Reprovada')

    prefeitura = models.ForeignKey('Prefeitura', on_delete=models.CASCADE, blank=False, null=False)
    lei_complementar = models.CharField(max_length=200, blank=True, null=True)
    data = models.DateField(_('Data'), blank=False, null=False)
    data_prevista = models.DateField(_('Data Prevista'), blank=False, null=False)
    valor_contrapartida = models.DecimalField(
        _('Valor da contrapartida'), max_digits=19, default=Decimal('0.00'), decimal_places=2, blank=False, null=False)
    valor_convenio = models.DecimalField(
        _('Valor do convênio'), max_digits=19, default=Decimal('0.00'), decimal_places=2, blank=True, null=True)
    valor_repasse = models.DecimalField(
        _('Valor do repasse'), max_digits=19, default=Decimal('0.00'), decimal_places=2, blank=True, null=True)
    valor_liberado = models.DecimalField(
        _('Valor liberado'), max_digits=19, default=Decimal('0.00'), decimal_places=2, blank=True, null=True)
    objeto = models.CharField(max_length=150, blank=True, null=True)
    numero = models.CharField(_('Número da proposta'), max_length=150, blank=False, null=False)
    situacao = models.CharField(
        max_length=15, choices=SituacaoChoice.choices, default=SituacaoChoice.EM_ANALISE, blank=True, null=True
    )
    extrato = models.FileField(upload_to='uploads/extrato/%Y/%m/%d', max_length=150, blank=True, null=True)
    data_criacao = models.DateField(_('Data de Criação'), auto_now=True, blank=False, null=False)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('proposta')
        verbose_name_plural = _('propostas')

    def __str__(self):
        return f'{self.numero} {self.objeto}'

    def verifica_situacao(self):
        if self.SituacaoChoice.EM_ANALISE == self.situacao:
            return self.SituacaoChoice.APROVADO
        if self.SituacaoChoice.APROVADO == self.situacao:
            return self.SituacaoChoice.EMPENHADO

    def verifica_valor_liberar(self):
        return self.valor_repasse - self.valor_liberado


class Convenio(models.Model):

    class SituacaoChoice(models.TextChoices):
        AGUARDANDO_APROVACAO_PROJETO = 'aguardando-aprovacao', _('Aguardando aprovação do projeto')
        PROJETO_APROVADO = 'projeto-aprovado', _('Projeto aprovado, aguardando licitação')
        AGUARDANDO_ACEITE_LICITACAO = 'aguardando-aceite-licitacao', _('Aguardando aceite da licitação')
        LICITACAO_APROVADA = 'licitacao-aprovada', _('Licitação aprovada, aguardando recurso')
        RECURSO_EM_CONTA = 'recurso-em-conta', _('Recurso em conta, em execução')
        CONVENIO_CONCLUIDO = 'convenio-concluido', _('Convenio concluído')
        PRESTACAO_DE_CONTAS_CONCLUIDA = 'prestacao-de-contas-concluida', _('Prestação de contas concluída')

    proposta = models.ForeignKey('Proposta', on_delete=models.CASCADE, blank=True, null=True)
    orgao = models.ForeignKey('Orgao', on_delete=models.CASCADE, blank=True, null=True)
    arquivo_extrato = models.FileField(upload_to='uploads/%Y/%m/%d', max_length=150, blank=True, null=True)
    numero = models.CharField(_('Número convênio (SICONV)'), max_length=150, blank=True, null=True)
    data_criacao = models.DateField(_('Data de Criação'), auto_now=True, blank=False, null=False)
    # data_criacao = models.DateTimeField(_('Data de Criação'), auto_now=True, blank=False, null=False)
    data_suspensiva = models.DateField(_('Data de Cláusula Suspensiva'), blank=True, null=True)
    data_vigencia = models.DateField(_('Data da Vigência'), blank=True, null=True)
    tecnico_orgao = models.ForeignKey('TecnicoOrgao', on_delete=models.CASCADE, blank=True, null=True)

    banco = models.CharField(max_length=200, blank=True, null=True)
    agencia = models.CharField(max_length=50, blank=True, null=True)
    conta = models.CharField(max_length=50, blank=True, null=True)

    data_aprovacao_projeto = models.DateField(_('Data Aprovação de Projeto'), blank=True, null=True)
    data_licitacao_projeto = models.DateField(_('Data Licitação de Projeto'), blank=True, null=True)
    data_analise_licitacao = models.DateField(_('Data Análise de Licitação'), blank=True, null=True)
    data_aceite_licitacao = models.DateField(_('Data Aceite de Licitação'), blank=True, null=True)
    data_liberacao_recurso = models.DateField(_('Data Liberação do Recurso'), blank=True, null=True)
    valor_recurso = models.DecimalField(
        _('Valor do recurso'), max_digits=19, default=Decimal('0.00'), decimal_places=2, blank=True, null=True)
    data_conclusao = models.DateField(_('Data Conclusão'), blank=True, null=True)
    data_prestacao_contas = models.DateField(_('Data Conclusão'), blank=True, null=True)

    nome_empresa_contratada = models.CharField(_('Empresa contratada'), max_length=250, blank=True, null=True)
    cnpj_empresa_contratada = models.CharField(_('CNPJ empresa contratada'), max_length=20, blank=True, null=True)
    numero_contrato = models.CharField(_('Número contrato'), max_length=150, blank=True, null=True)
    data_contrato = models.DateField(_('Data contrato'), max_length=150, blank=True, null=True)
    vigencia_contrato = models.DateField(_('Vigência contrato'), max_length=150, blank=True, null=True)
    valor_contrato = models.DecimalField(
        _('Valor contrato'), max_digits=19, default=Decimal('0.00'), decimal_places=2, blank=True, null=True)

    situacao = models.CharField(
        max_length=50,
        choices=SituacaoChoice.choices,
        default=SituacaoChoice.AGUARDANDO_APROVACAO_PROJETO,
        blank=True,
        null=True
    )
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('convênio')
        verbose_name_plural = _('convênios')

    def __str__(self):
        return f'{self.proposta}'


class ExecucaoConvenente(models.Model):
    convenio = models.ForeignKey(
        'Convenio',
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )
    parcela = models.IntegerField(
        _('Parcela'),
        blank=False,
        null=False
    )
    data_pagamento = models.DateField(
        _('Data pagamento'),
        blank=False,
        null=False
    )
    valor_pagamento = models.DecimalField(
        _('Valor pagamento'),
        max_digits=19,
        default=Decimal('0.00'),

core/reports/models.py
# from django.db import models

# Create your models here.

core/reports/templates/reports/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Agiliza - Página inicial</title>
		<!-- <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/> -->
		<!-- CSS -->
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="{% static 'css/all.css' %}">
		<link rel="stylesheet" href="{% static 'css/font-default.css' %}">
		<!-- <link href="https://fonts.googleapis.com/css2?family=Viga&display=swap" rel="stylesheet"> -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'css/alertify.css' %}">
		<link rel="stylesheet" href="{% static 'css/alertify/themes/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'css/autocomplete.css' %}">
		<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
		<!-- XDSoft DateTimePicker -->
		<link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

		<style>
			/*thead, tfoot { display: table-row-group !important }*/
			thead { display: table-header-group !important; }
			tfoot { display: table-row-group !important; }
			tr { page-break-inside: avoid !important; }
		</style>	
	</head>
	<body>

		<div class="container-fluid"> 
			<div class="row">
				<main class="col-md-12 ml-sm-auto col-lg-12" role="main">
					{% block body %}
					{% endblock %}
				</main>
			</div>

		</div>

		{% include 'base/footer.html' %}

	</body>
</html>

core/reports/templates/reports/convenio_projeto_controle.html
{% extends 'reports/base.html' %}

{% block body %}

<h1>{{ title }}</h1>

<div class="row">
	<div class="col-md-12">

		{% if controle %}
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Orgão</th>
					<th>Projeto</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>{{ controle.orgao }}</td>
					<td>{{ controle.projeto.get_tipo_display }}</td>
				</tr>
			</tbody>
		</table>
		{% else %}
		<div class="alert alert-info mb-0">Nenhum projeto criado!</div>
		<br>
		{% endif %}
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>Item</th>
					<th>Opção</th>
					<th>Responsável</th>
					<th style="white-space: nowrap;">Data Prevista</th>
				</tr>
			</thead>
			<tbody>
				{% if itens %}
				{% for item in itens %}
				<tr class="item-controle">
					<td>
						<div class="descricao"><a href="javascript: void(0);" class="botao_submeter_item_controle" data-posicao="{{ forloop.counter0 }}" data-item-id="{{ item.id }}" data-id="{{ item.item_controle.id|default:False }}" onclick="abrirItemModal(this)">{{ item.descricao }}</a></div>
						<div class="observacoes text-danger">{{ item.item_controle.observacoes }}</div>
					</td>
					<td class="alternativa">{{ item.item_controle.alternativa|default:"" }}</td>
					<td class="responsavel">{{ item.item_controle.responsavel|default:"" }}</td>
					<td class="data_prevista">{{ item.item_controle.data_prevista|date:"d/m/Y"|default:"" }}</td>
				</tr>
				{% endfor %}
				{% endif %}
			</tbody>
		</table>
	</div>
</div>

{% endblock %}

core/reports/templates/reports/convenios.html
{% extends 'reports/base.html' %}

{% block body %}
<h1>{{ title }}</h1>
<div class="row">
	<div class="col-md-12">
		{% if convenios %}
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>Número Convênio</th>
					<th>Proposta</th>
					<th>Objeto</th>
					<th>Prefeitura</th>
					<th width="1%">R$ Valor</th>
				</tr>
			</thead>
			<tbody>
				{% for convenio in convenios %}
				<tr>
					<td>{{ convenio.numero }}</td>
					<td><a href="{% url 'proposta' convenio.proposta.id %}">{{ convenio.proposta.numero }}</a></td>
					<td>{{ convenio.proposta.objeto }}</td>
					<td>{{ convenio.proposta.prefeitura }}</td>
					<td class="text-right">{% load l10n %}{{ convenio.proposta.valor_convenio|floatformat:2|localize }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
		<div class="alert alert-info mb-0">Nenhum convenio cadastrado!</div>
		{% endif %}
	</div>
</div>
{% endblock %}

core/reports/templates/reports/my_template.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1>Hello world!!!</h1>	
</body>
</html>

core/reports/templates/reports/propostas.html
{% extends 'reports/base.html' %}

{% block body %}
<h1>{{ title }}</h1>
<div class="row">
	<div class="col-md-12">
		<table class="table table-bordered">
			<thead>
				<tr>
					<!-- <th class="p-0" width="1%"> </th> -->
					<!-- <th width="1%"><i class="fas fa-asterisk"></i></th> -->
					<th>Prefeitura</th>
					<th>Número</th>
					<th>Objeto</th>
					<th>R$ Valor Convênio</th>
					<th>Data</th>
					<th>Situação</th>
				</tr>
			</thead>
			<tbody>
				{% for proposta in propostas %}
				<tr>
					<!-- <td class="text-center"><i class="fas fa-caret-right"></i></td> -->
					<td>{{ proposta.prefeitura }}</td>
					<td>{{ proposta.numero }}</td>
					<td>{{ proposta.objeto }}</td>
					<td class="text-right">{% load l10n %}{{ proposta.valor_convenio|floatformat:2|localize }}</td>
					<td>{{ proposta.data|date:"d/m/Y" }}</td>
					<td class="text-center">{{ proposta.get_situacao_display }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% if not propostas %}
			<div class="alert alert-info mb-0">Nenhuma proposta cadastrada!</div>
		{% endif %}
	</div>
</div>
{% endblock %}

core/reports/templates/reports/servicos.html
{% extends 'reports/base.html' %}

{% block body %}
<h1>{{ title }}</h1>
<div class="row">
	<div class="col-md-12">
		<table class="table table-bordered">
			<thead>
				<tr>
					<!-- <th class="p-0" width="1%"> </th> -->
					<th width="1%"><i class="fas fa-asterisk"></i></th>
					<th>Prefeitura</th>
					<th>Objeto</th>
					<th>Observações</th>
					<th>Responsáveis</th>
					<th>Data de Cadastro</th>
					<th>Data Prevista</th>
				</tr>
			</thead>
			<tbody>
				{% for servico in servicos %}
				<tr>
					<!-- <td class="text-center"><i class="fas fa-caret-right"></i></td> -->
					<td class="text-center">
					</td>
					<td>{{ servico.prefeitura }}</td>
					<td>{{ servico.objeto }}</td>
					<td>{{ servico.observacoes }}</td>
					<td>{{ servico.responsavel }}</td>
					<td class="text-center">{{ servico.data_cadastro|date:"d/m/Y" }}</td>
					<td class="text-center">{{ servico.data_prevista|date:"d/m/Y" }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% if not servicos %}
			<div class="alert alert-info mb-0">Nenhum serviço cadastrado!</div>
		{% endif %}
	</div>
</div>
{% endblock %}